bot_token = "" #Just the token, no "Bot" prefix
bridge_channel_id = 0
server_logfile = ""
admin_user_id = 0
server_dir = "/home/user/terraria-server"

[postgres]
host = "localhost"
port = 5432
user = ""
pass = ""
dbname = "terraria"

[tcpdump]
interface = "enp1s0"
port = 7777
