bot_token = "" #Just the token, no "Bot" prefix
bridge_channel_id = 0
journalctl_unit = "terraria.service"
socket_path = "/run/terraria.stdin"

[postgres]
host = "localhost"
port = 5432
user = ""
pass = ""
dbname = "terraria"

[tcpdump]
interface = "enp1s0"
port = 7777
